//! Self-serve agent installation.
//!
//! The portal hands out the agent binary and a script that installs it, so
//! adding a machine is one line rather than a page of copy-paste. The script
//! is generated per-request from the `Host:` header the client actually used,
//! which means the address baked into it is by definition one that reaches us —
//! no guessing at our own IP, and it keeps working when DHCP moves us.
//!
//! These routes are deliberately unauthenticated: they contain no secret. The
//! enrolment token is passed as an argument by whoever runs the script, so
//! `curl | sh` works whether or not admin auth is enabled.

use axum::extract::{Path, State};
use axum::http::{header, HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::Router;

use crate::state::SharedState;

pub fn routes(state: SharedState) -> Router {
    Router::new()
        .route("/install.sh", get(install_sh))
        .route("/install.ps1", get(install_ps1))
        .route("/download/{file}", get(download))
        .with_state(state)
}

/// The address the client used to reach us. Falls back to the configured bind
/// address only if a client somehow omits `Host`.
fn portal_host(headers: &HeaderMap, state: &SharedState) -> String {
    headers
        .get(header::HOST)
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string())
        .unwrap_or_else(|| state.public_host.clone())
}

/// Files we are willing to serve. An allow-list rather than path joining,
/// because this endpoint is unauthenticated and reachable by anyone who can
/// see the port.
const SERVABLE: &[(&str, &str)] = &[
    ("pp-agent", "application/octet-stream"),
    ("pp-agent.exe", "application/octet-stream"),
    ("patchpanel-agent.service", "text/plain; charset=utf-8"),
];

async fn download(Path(file): Path<String>, State(state): State<SharedState>) -> Response {
    let Some((name, mime)) = SERVABLE.iter().find(|(n, _)| *n == file) else {
        return (StatusCode::NOT_FOUND, "no such file\n").into_response();
    };

    let path = state.agent_dir.join(name);
    match tokio::fs::read(&path).await {
        Ok(bytes) => (
            [
                (header::CONTENT_TYPE, *mime),
                (header::CACHE_CONTROL, "no-store"),
            ],
            bytes,
        )
            .into_response(),
        Err(e) => {
            tracing::warn!(path = %path.display(), error = %e, "agent artefact not available");
            (
                StatusCode::NOT_FOUND,
                format!(
                    "`{name}` is not published on this portal.\n\
                     Put it in {} and it will be served here.\n",
                    state.agent_dir.display()
                ),
            )
                .into_response()
        }
    }
}

async fn install_sh(headers: HeaderMap, State(state): State<SharedState>) -> Response {
    let host = portal_host(&headers, &state);
    let script = format!(
        r#"#!/bin/sh
# PatchPanel agent installer. Generated by the portal at {host}.
set -eu

PORTAL="{host}"
TOKEN=""
SITE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --token) TOKEN="${{2:-}}"; shift 2 ;;
    --site)  SITE="${{2:-}}";  shift 2 ;;
    -h|--help)
      echo "usage: install.sh --token <enrollment-token> [--site <name>]"
      exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 64 ;;
  esac
done

# No --token is fine: the agent asks the portal for one, which works when the
# portal runs without admin auth. It fails with a clear message otherwise.
[ "$(id -u)" = "0" ] || {{ echo "error: run this as root" >&2; exit 1; }}
[ -n "$SITE" ] || SITE="$(hostname)"

command -v systemctl >/dev/null 2>&1 || {{ echo "error: this installer needs systemd" >&2; exit 1; }}

echo "==> downloading agent"
# Download beside the target and rename, so an interrupted fetch never leaves a
# half-written binary where systemd expects a working one.
curl -fsSL "http://$PORTAL/download/pp-agent" -o /usr/local/bin/.pp-agent.new
chmod 0755 /usr/local/bin/.pp-agent.new
mv /usr/local/bin/.pp-agent.new /usr/local/bin/pp-agent

# The agent installs itself: writes config, drops the unit, enables and starts.
# Keeping that logic in the binary means the shell script cannot get it wrong.
if [ -n "$TOKEN" ]; then
  /usr/local/bin/pp-agent setup --portal "$PORTAL" --token "$TOKEN"     --site "$SITE" --state-dir /var/lib/patchpanel
else
  /usr/local/bin/pp-agent setup --portal "$PORTAL"     --site "$SITE" --state-dir /var/lib/patchpanel
fi

sleep 2
if systemctl is-active --quiet patchpanel-agent; then
  echo "==> done. this machine now reports to http://$PORTAL/"
  echo "    logs: journalctl -u patchpanel-agent -f"
else
  echo "!! the service did not start; see: journalctl -u patchpanel-agent -n 50" >&2
  exit 1
fi
"#
    );

    (
        [
            (header::CONTENT_TYPE, "text/x-shellscript; charset=utf-8"),
            (header::CACHE_CONTROL, "no-store"),
        ],
        script,
    )
        .into_response()
}

async fn install_ps1(headers: HeaderMap, State(state): State<SharedState>) -> Response {
    let host = portal_host(&headers, &state);
    let script = format!(
        r#"# PatchPanel agent installer. Generated by the portal at {host}.
# Run from an ELEVATED PowerShell prompt.
[CmdletBinding()]
param(
  [Parameter(Mandatory)][string] $Token,
  [string] $Site = $env:COMPUTERNAME,
  [string] $InstallDir = "$env:ProgramFiles\PatchPanel"
)

$ErrorActionPreference = 'Stop'
$Portal = '{host}'

# Windows PowerShell 5.1 renders a progress bar for every chunk of
# Invoke-WebRequest, which turns a 6 MB download into minutes. Silencing it is
# the difference between this feeling instant and feeling broken.
$ProgressPreference = 'SilentlyContinue'

# 5.1 negotiates TLS 1.0 by default; harmless over plain HTTP, but it means
# this still works if the portal is later put behind HTTPS.
try {{
  [Net.ServicePointManager]::SecurityProtocol =
    [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
}} catch {{ }}

$principal = New-Object Security.Principal.WindowsPrincipal(
  [Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
  throw "Run this from an elevated PowerShell prompt."
}}

$service = 'PatchPanelAgent'
$target  = Join-Path $InstallDir 'pp-agent.exe'

# Windows will not overwrite a running image, so stop first.
if (Get-Service -Name $service -ErrorAction SilentlyContinue) {{
  Write-Host '==> stopping existing service'
  Stop-Service -Name $service -Force -ErrorAction SilentlyContinue
  Start-Sleep -Seconds 2
}}

Write-Host '==> downloading agent'
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Invoke-WebRequest -UseBasicParsing -Uri "http://$Portal/download/pp-agent.exe" -OutFile "$target.new"
Move-Item -Force "$target.new" $target

# The agent installs itself from here: config, service registration, start.
& $target setup --portal "ws://$Portal/api/agent/ws" --token $Token --site $Site
if ($LASTEXITCODE -ne 0) {{ throw "Setup failed ($LASTEXITCODE)." }}

Start-Service -Name $service
Start-Sleep -Seconds 2
if ((Get-Service $service).Status -eq 'Running') {{
  Write-Host "==> done. this machine now reports to http://$Portal/"
}} else {{
  throw "The service did not start. Check: Get-Service $service"
}}
"#
    );

    (
        [
            (header::CONTENT_TYPE, "text/plain; charset=utf-8"),
            (header::CACHE_CONTROL, "no-store"),
        ],
        script,
    )
        .into_response()
}
